plugins {
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'org.roguegame'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation ('org.junit.jupiter:junit-jupiter')
    // прокидываем лантерну
    implementation("com.googlecode.lanterna:lanterna:3.1.2")
    }

test {
    useJUnitPlatform()
}

run {
    standardInput = System.in
    systemProperty 'java.library.path', 'libs'
}

application {
    mainClass = 'Main'

}

// интегрируем плагин для сборки джарника со всеми плагинами
shadowJar {
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}

